# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/run/media/sbakaj/Nový svazek/VS/5_semestr/ISA/ISA_Project2022"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/run/media/sbakaj/Nový svazek/VS/5_semestr/ISA/ISA_Project2022"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/run/media/sbakaj/Nový svazek/VS/5_semestr/ISA/ISA_Project2022/CMakeFiles" "/run/media/sbakaj/Nový svazek/VS/5_semestr/ISA/ISA_Project2022//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/run/media/sbakaj/Nový svazek/VS/5_semestr/ISA/ISA_Project2022/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ISA_Project2022

# Build rule for target.
ISA_Project2022: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ISA_Project2022
.PHONY : ISA_Project2022

# fast build rule for target.
ISA_Project2022/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/build
.PHONY : ISA_Project2022/fast

error.o: error.cpp.o
.PHONY : error.o

# target to build an object file
error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/error.cpp.o
.PHONY : error.cpp.o

error.i: error.cpp.i
.PHONY : error.i

# target to preprocess a source file
error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/error.cpp.i
.PHONY : error.cpp.i

error.s: error.cpp.s
.PHONY : error.s

# target to generate assembly for a file
error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/error.cpp.s
.PHONY : error.cpp.s

flows.o: flows.cpp.o
.PHONY : flows.o

# target to build an object file
flows.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/flows.cpp.o
.PHONY : flows.cpp.o

flows.i: flows.cpp.i
.PHONY : flows.i

# target to preprocess a source file
flows.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/flows.cpp.i
.PHONY : flows.cpp.i

flows.s: flows.cpp.s
.PHONY : flows.s

# target to generate assembly for a file
flows.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/flows.cpp.s
.PHONY : flows.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/main.cpp.s
.PHONY : main.cpp.s

parameters.o: parameters.cpp.o
.PHONY : parameters.o

# target to build an object file
parameters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/parameters.cpp.o
.PHONY : parameters.cpp.o

parameters.i: parameters.cpp.i
.PHONY : parameters.i

# target to preprocess a source file
parameters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/parameters.cpp.i
.PHONY : parameters.cpp.i

parameters.s: parameters.cpp.s
.PHONY : parameters.s

# target to generate assembly for a file
parameters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/parameters.cpp.s
.PHONY : parameters.cpp.s

udp_client.o: udp_client.cpp.o
.PHONY : udp_client.o

# target to build an object file
udp_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/udp_client.cpp.o
.PHONY : udp_client.cpp.o

udp_client.i: udp_client.cpp.i
.PHONY : udp_client.i

# target to preprocess a source file
udp_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/udp_client.cpp.i
.PHONY : udp_client.cpp.i

udp_client.s: udp_client.cpp.s
.PHONY : udp_client.s

# target to generate assembly for a file
udp_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ISA_Project2022.dir/build.make CMakeFiles/ISA_Project2022.dir/udp_client.cpp.s
.PHONY : udp_client.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ISA_Project2022"
	@echo "... error.o"
	@echo "... error.i"
	@echo "... error.s"
	@echo "... flows.o"
	@echo "... flows.i"
	@echo "... flows.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parameters.o"
	@echo "... parameters.i"
	@echo "... parameters.s"
	@echo "... udp_client.o"
	@echo "... udp_client.i"
	@echo "... udp_client.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

